language: node_js
node_js: ["lts/carbon"]
cache:
  directories:
    - node_modules
    - captain-fact-overlay-injector/node_modules
install:
  - cd captain-fact-overlay-injector
  - npm install
  - npm run build
  - cd ..
  - npm install
script:
  - npm run coverage && cat ./coverage/lcov.info | coveralls
